# Binding health checks to an internal port
management.port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health.enabled: true

logging.config:
  classpath: logback.xml

# The name of the Camel app
camel.springboot:
  name: CamelAMQPExample
  main-run-controller: true

amqp:
  url: amqp://localhost:5672
#  url: amqps://localhost:5671?transport.trustStoreLocation=/home/user/AppServers/examplebroker/etc/client_ts.p12&transport.trustStorePassword=password&transport.verifyHost=false&jms.sendTimeout=5000
  username: theuser
  password: Thepassword1!





